INSERT INTO info (url, file_name, message, category, stack_trace, line_number, column_number, user_agent, date, cookie, remarks) VALUES ('http://example.com1', 'index.html', 'ReferenceError: hoge', 'ReferenceError', 'stacktrace', 0, 0, '', current_time, '', '');
INSERT INTO info (url, file_name, message, category, stack_trace, line_number, column_number, user_agent, date, cookie, remarks) VALUES ('http://example.com2', 'index.html', 'ReferenceError: hoge', 'ReferenceError', '', 0, 0, '', current_time, '', '');
INSERT INTO info (url, file_name, message, category, stack_trace, line_number, column_number, user_agent, date, cookie, remarks) VALUES ('http://example.com3', 'index.html', 'ReferenceError: hoge', 'ReferenceError', '', 0, 0, '', current_time, '', '');
INSERT INTO info (url, file_name, message, category, stack_trace, line_number, column_number, user_agent, date, cookie, remarks) VALUES ('http://example.com4', 'index.html', 'ReferenceError: hoge', 'ReferenceError', '', 0, 0, '', current_time, '', '');
INSERT INTO info (url, file_name, message, category, stack_trace, line_number, column_number, user_agent, date, cookie, remarks) VALUES ('http://example.com5', 'index.html', 'ReferenceError: hoge', 'ReferenceError', '', 0, 0, '', current_time, '', '');
INSERT INTO info (url, file_name, message, category, stack_trace, line_number, column_number, user_agent, date, cookie, remarks) VALUES ('http://example.com6', 'index.html', 'TypeError: hoge', 'TypeError', '', 0, 0, '', current_time, '', '');
INSERT INTO info (url, file_name, message, category, stack_trace, line_number, column_number, user_agent, date, cookie, remarks) VALUES ('http://example.com7', 'index.html', 'TypeError: hoge', 'TypeError', '', 0, 0, '', current_time, '', '');
INSERT INTO info (url, file_name, message, category, stack_trace, line_number, column_number, user_agent, date, cookie, remarks) VALUES ('http://example.com8', 'index.html', 'TypeError: hoge', 'TypeError', '', 0, 0, '', current_time, '', '');
INSERT INTO info (url, file_name, message, category, stack_trace, line_number, column_number, user_agent, date, cookie, remarks) VALUES ('http://example.com9', 'index.html', 'TypeError: hoge', 'TypeError', '', 0, 0, '', current_time, '', '');
INSERT INTO info (url, file_name, message, category, stack_trace, line_number, column_number, user_agent, date, cookie, remarks) VALUES ('http://example.com10', 'index.html', 'SyntaxError: hoge', 'SyntaxError', '', 0, 0, '', current_time, '', '');
INSERT INTO info (url, file_name, message, category, stack_trace, line_number, column_number, user_agent, date, cookie, remarks) VALUES ('http://example.com11', 'index.html', 'SyntaxError: hoge', 'SyntaxError', '', 0, 0, '', current_time, '', '');
INSERT INTO info (url, file_name, message, category, stack_trace, line_number, column_number, user_agent, date, cookie, remarks) VALUES ('http://example.com12', 'index.html', 'SyntaxError: hoge', 'SyntaxError', '', 0, 0, '', current_time, '', '');
INSERT INTO info (url, file_name, message, category, stack_trace, line_number, column_number, user_agent, date, cookie, remarks) VALUES ('http://example.com13', 'index.html', 'SyntaxError: hoge', 'SyntaxError', '', 0, 0, '', current_time, '', '');

