INSERT INTO info (url, file_name, message, category, stack_trace, line_number, column_number, user_agent, date, cookie, remarks) VALUES ('http://www.hoge.com/test1?id=123',     'index.html', 'ReferenceError: hoge', 'ReferenceError', 'stacktrace', 0, 0, 'Firefox', current_timestamp, '', '');
INSERT INTO info (url, file_name, message, category, stack_trace, line_number, column_number, user_agent, date, cookie, remarks) VALUES ('http://www.example.com/test2',  'index.html', 'ReferenceError: hoge', 'ReferenceError', 'stacktrace', 0, 0, 'Firefox', current_timestamp, '', '');
INSERT INTO info (url, file_name, message, category, stack_trace, line_number, column_number, user_agent, date, cookie, remarks) VALUES ('http://www.example.com/test3',  'index.html', 'ReferenceError: hoge', 'ReferenceError', 'stacktrace', 0, 0, 'Firefox', current_timestamp, '', '');
INSERT INTO info (url, file_name, message, category, stack_trace, line_number, column_number, user_agent, date, cookie, remarks) VALUES ('http://www.example.com/test4',  'index.html', 'ReferenceError: hoge', 'ReferenceError', 'stacktrace', 0, 0, 'Firefox', current_timestamp, '', '');
INSERT INTO info (url, file_name, message, category, stack_trace, line_number, column_number, user_agent, date, cookie, remarks) VALUES ('http://www.example.com/test5',  'index.html', 'ReferenceError: hoge', 'ReferenceError', 'stacktrace', 0, 0, 'Firefox', current_timestamp, '', '');
INSERT INTO info (url, file_name, message, category, stack_trace, line_number, column_number, user_agent, date, cookie, remarks) VALUES ('http://www.example.com/test6',  'index.html', 'TypeError: hoge',      'TypeError',      'stacktrace', 0, 0, 'Firefox', current_timestamp, '', '');
INSERT INTO info (url, file_name, message, category, stack_trace, line_number, column_number, user_agent, date, cookie, remarks) VALUES ('http://www.example.com/test7',  'index.html', 'TypeError: hoge',      'TypeError',      'stacktrace', 0, 0, 'Firefox', current_timestamp, '', '');
INSERT INTO info (url, file_name, message, category, stack_trace, line_number, column_number, user_agent, date, cookie, remarks) VALUES ('http://www.example.com/test8',  'index.html', 'TypeError: hoge',      'TypeError',      'stacktrace', 0, 0, 'Firefox', current_timestamp, '', '');
INSERT INTO info (url, file_name, message, category, stack_trace, line_number, column_number, user_agent, date, cookie, remarks) VALUES ('http://www.example.com/test9',  'index.html', 'TypeError: hoge',      'TypeError',      'stacktrace', 0, 0, 'Firefox', current_timestamp, '', '');
INSERT INTO info (url, file_name, message, category, stack_trace, line_number, column_number, user_agent, date, cookie, remarks) VALUES ('http://www.example.com/test10', 'index.html', 'SyntaxError: hoge',    'SyntaxError',    'stacktrace', 0, 0, 'Firefox', current_timestamp, '', '');
INSERT INTO info (url, file_name, message, category, stack_trace, line_number, column_number, user_agent, date, cookie, remarks) VALUES ('http://www.example.com/test11', 'index.html', 'SyntaxError: hoge',    'SyntaxError',    'stacktrace', 0, 0, 'Firefox', current_timestamp, '', '');
INSERT INTO info (url, file_name, message, category, stack_trace, line_number, column_number, user_agent, date, cookie, remarks) VALUES ('http://www.example.com/test12', 'index.html', 'SyntaxError: hoge',    'SyntaxError',    'stacktrace', 0, 0, 'Firefox', current_timestamp, '', '');
INSERT INTO info (url, file_name, message, category, stack_trace, line_number, column_number, user_agent, date, cookie, remarks) VALUES ('http://www.example.com/test13', 'index.html', 'SyntaxError: hoge',    'SyntaxError',    'stacktrace', 0, 0, 'Firefox', current_timestamp, '', '');

